## Credit - https://github.com/Sushrut1101
env:
    MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
    DEVICE: RMX1851
    OEM: realme
    DT_LINK: https://github.com/Think-Thought/RMX1851_TWRP.git -b master
    DT_PATH: device/$OEM/$DEVICE
    OUTPUT: recovery.img

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "TWRP Builder CI"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Build_clone_script:
      - repo init -u $MANIFEST
      - repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags
      - repo sync --force-sync
      - git clone $DT_LINK $DT_PATH
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/building.sh | bash

  Uploading_script:
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/uploading.sh | bash
