## Credit - https://github.com/Sushrut1101
env:
    MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
    DEVICE: RMX1851
    OEM: realme
    DT_LINK: https://github.com/Think-Thought/android_device_realme_RMX1851-twrp.git -b a11-RUI2
    DT_PATH: device/$OEM/$DEVICE
    TARGET: recoveryimage
    LUNCH_COMBO: twrp_$Device-eng
    OUTPUT: recovery.img

task:
  name: "TWRP Builder CI"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  clone_script:
      - repo init -u $MANIFEST
      - repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags
      - repo sync --force-sync
      - git clone $DT_LINK $DT_PATH
      - . build/envsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - lunch "$LUNCH_COMBO"
      - mka -j$(nproc) $TARGET

  Uploading_script:
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
